name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # ou '16', dependendo da versão que você está usando

    - name: Install dependencies
      run: npm install

    - name: Start Angular server
      run: ng serve --port 4200 --disable-host-check

    # Você pode adicionar mais etapas aqui, como testes, se necessário
